spring:
  datasource:
    url : jdbc:mysql://103.186.184.26:3306/ehr_sit?useUnicode=yes&characterEncoding=UTF-8
    username: remote_sit
    password: Remote@123

    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle : true
      initial-size: 5
      max-active: 50
      max-idle: 20
      min-idle: 10
      # max-wait time is in milliseconds
      max-wait: 20000

  jpa :
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy : org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect






