spring:
  datasource:
    url: jdbc:oracle:thin:@//103.186.184.26:1521/ORCLPDB1
    username: remote_sit
    password: Remote@123
    driver-class-name: oracle.jdbc.OracleDriver
    tomcat:
      test-while-idle: true
      initial-size: 5
      max-active: 50
      max-idle: 20
      min-idle: 10
      max-wait: 20000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
