spring:
  datasource:
    url: jdbc:oracle:thin:@10.43.50.201:1552:itmsuat
    username: AUTOSYS
    password: AUTOSYS_123
    driver-class-name: oracle.jdbc.OracleDriver

    tomcat:
      test-while-idle: true
      initial-size: 5
      max-total: 50 
      max-idle: 20
      min-idle: 10
      max-wait: 20000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
