spring:
  application:
    name: user-service
  profiles:
    active: main

server:
  servlet:
    context-path: /user-service
  port: 8081

---

spring:
  config:
    activate:
      on-profile: main
  cloud:
    config:
      uri: http://localhost:9001/config-server
