spring:
  application:
    name: user-service
  profiles:
    active: main

server:
  servlet:
    context-path: /user-service
  port: 8081

---
spring:
  config:
    activate:
      on-profile: main