spring:
  application:
    name: user-service
  profiles:
    active: sit

server:
  servlet:
    context-path: /user-service
  port: 8081

---

spring:
  config:
    activate:
      on-profile: sit
  cloud:
    config:
      uri: http://localhost:9001/config-server
