spring:
  application:
    name: user-service
  profiles:
    active: sit
  
server:
  contextPath: /user-service
  port: 8081

---
spring:
  profiles: sit
  cloud:
    config:
      uri: http://localhost:9001/config-server
