spring:
  application:
    name: report-service
  profiles:
    active: sit
  
server:
  port: 9888

feign:
  client:
    config:
      default:
        connectTimeout: 160000
        readTimeout: 160000

hystrix:  
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 210000
  threadpool:
    default:
      coreSize: 50
      maxQueueSize: 100
      queueSizeRejectionThreshold: 50

security:
  basic:
    enabled: false

management:
  security:
    enabled: false
    
pdf:
 dirPath : E:\pdf\
 imagePath : /home/hra/uat/images/defaultimage.png       
 waterMarkPath: /home/hra/uat/pdf/
 emailaddress: /home/hra/uat/pdf/
 waterMarkEnabled: false

template:
  assessmentIndividualInsightTemplatePath: /home/hra/backend/ehr-product/reflection/report-service/src/main/resources/templates/assessmentIndividualInsight.vm
  assessmentCorporateInsightTemplatePath: /home/hra/backend/ehr-product/reflection/report-service/src/main/resources/templates/assessmentCorporateInsight.vm
 
    

---
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: sit
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
        root: /services
        instance-port: ${server.port}
        instance-id: ${spring.application.name}:${server.port}

  quartz:
    job-store-type: memory  # Use in-memory Quartz scheduling (no database tables)
    properties:
      org.quartz.scheduler.instanceName: ReportScheduler
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.threadPool.threadCount: 10
      org.quartz.jobStore.class: org.quartz.simpl.RAMJobStore  # Store jobs in memory
      org.quartz.jobStore.misfireThreshold: 60000
