server:
  port: 9000
  servlet:
    context-path: /discovery-service

    

spring:
  jmx:
    default-domain: discovery-service
  profiles :
     active : sit
  application:
    name: discovery-service
  cloud:
      zookeeper:
        connect-string: localhost:2181
        discovery:
          enabled: true
          root: /services
          instance-port: ${server.port}
          instance-id: ${spring.application.name}:${server.port}