spring:
  application:
    name: health-company-service
  profiles:
    active: sit
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
    
server:
  port: 9005  
  tomcat:
    max-http-form-post-size: 20971520  # 20 MB
      

feign:
  client:
    config:
      default:
        retryer:
          period: 1000                # Initial retry interval in milliseconds
          max-period: 5000            # Maximum retry interval in milliseconds
          max-attempts: 3             # Maximum number of retry attempts
        connectTimeout: 10000         # Connection timeout in milliseconds
        readTimeout: 10000    


  
        

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 210000
  threadpool:
    default:
      coreSize: 50
      maxQueueSize: 100
      queueSizeRejectionThreshold: 50

security:
 basic:
   enabled: false

management:
 security:
   enabled: false
    
message:
  sendotp : 1234
  
whiteLable : 'ECATC001'
coBranding : 'ECATC002'
noBranding : 'ECATC003'

---
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: sit                 
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
        root: /services
        instance-port: ${server.port}
        instance-id: ${spring.application.name}:${server.port}     
