INSERT INTO ehr_sit.terms_condition_master
(`date`, portal, terms_condition_body, version)
VALUES
('2025-01-10 16:44:25.693000', 'company', '<body style="font-size: 15px; letter-spacing: 0.55px;" >
    <div>
        <h6 style="margin-bottom: 0px;">TERMS OF USE </h6>
        <P style="margin-top: 0px; margin-bottom: 10px; font-size: 10px;">Welcome to ehr.com EHR and/or its affiliates provide website features and other products
            and services to you when you visit or shop at essayliving.com use Essay Living products or services, or use
            the software provided by Essay Living in connection with any of the foregoing. Essay Living provides the
            Services subject to the following conditions. This user agreement (“Terms and Conditions” or “T&C” or
            “Terms” or “Agreement”) is between you (“you” or “End User” or “your” or “Buyer” or “Customer” or
            “Registered User”) and Essay Living (“Company” or “us” or “we” or “essayliving.com”). This document is an
            electronic record in terms of the Information Technology Act, 2000 and rules there under as applicable and
            the amended provisions about electronic records in various statutes as amended by the Information Technology
            Act, 2000. This electronic record is generated by a computer system and does not require any physical or
            digital signatures. Notwithstanding anything contained or said in any other document, if there is a conflict
            between the terms mentioned herein below and any other document, the terms contained in the present T&C
            shall alone prevail for usage of the Site. </P>

        <h6 style="margin-bottom: 0px;">RIGHT TO CHANGE</h6>
        <p style="margin-top: 0px; margin-bottom: 10px; font-size: 10px;">EHR reserves the exclusive right to update or modify its Terms and Conditions at any time without
            prior notice. We, therefore, recommend that you review these Terms and Conditions every time you purchase
            products or use our website. </p>

        <h6 style="margin-bottom: 0px;">PRIVACY</h6>
        <p style="margin-top: 0px; margin-bottom: 10px; font-size: 10px;"> At our company, we consider the protection of your privacy as a crucial
            principle. We understand that your personal information is one of our most critical assets. We store and
            process your information, including any sensitive financial information (as defined under the Information
            Technology Act, 2000), if any, on computers that are safeguarded by physical as well as reasonable
            technological security measures and procedures, as prescribed by the Information Technology Act 2000 and the
            rules thereunder. If you disagree with our current privacy policy or the way your information is being used
            or transferred, please refrain from using our website. </p>
        <h6 style="margin-bottom: 0px;">ELECTRONIC COMMUNICATIONS </h6>
        <p style="margin-top: 0px; margin-bottom: 10px; font-size: 10px;">When you use any of our services or send emails to us, you are communicating with us electronically. By using
            our services, you consent to receive electronic communications from us. We will communicate with you through
            email or by posting notices on our website or other services. You agree that all agreements, notices,
            disclosures, and other communications that we provide to you electronically fulfil any legal requirement
            that such communications be in writing. These legal requirements are in accordance with the Indian
            Information Technology Act, 2000, and its applicable rules, as well as the amended provisions regarding
            electronic records in various statutes, as amended by the Information Technology Act, 2000.</p>
    </div>
</body>
', 'V1'),
('2025-01-10 17:44:25.693000', 'company', '<body style="font-size: 15px; letter-spacing: 0.55px;" >
    <div>
        <h6 style="margin-bottom: 0px;">TERMS OF USE </h6>
        <P style="margin-top: 0px; margin-bottom: 10px; font-size: 10px;">Welcome to ehr.com EHR and/or its affiliates provide website features and other products
            and services to you when you visit or shop at essayliving.com use Essay Living products or services, or use
            the software provided by Essay Living in connection with any of the foregoing. Essay Living provides the
            Services subject to the following conditions. This user agreement (“Terms and Conditions” or “T&C” or
            “Terms” or “Agreement”) is between you (“you” or “End User” or “your” or “Buyer” or “Customer” or
            “Registered User”) and Essay Living (“Company” or “us” or “we” or “essayliving.com”). This document is an
            electronic record in terms of the Information Technology Act, 2000 and rules there under as applicable and
            the amended provisions about electronic records in various statutes as amended by the Information Technology
            Act, 2000. This electronic record is generated by a computer system and does not require any physical or
            digital signatures. Notwithstanding anything contained or said in any other document, if there is a conflict
            between the terms mentioned herein below and any other document, the terms contained in the present T&C
            shall alone prevail for usage of the Site. </P>

        <h6 style="margin-bottom: 0px;">RIGHT TO CHANGE</h6>
        <p style="margin-top: 0px; margin-bottom: 10px; font-size: 10px;">EHR reserves the exclusive right to update or modify its Terms and Conditions at any time without
            prior notice. We, therefore, recommend that you review these Terms and Conditions every time you purchase
            products or use our website. </p>

        <h6 style="margin-bottom: 0px;">PRIVACY</h6>
        <p style="margin-top: 0px; margin-bottom: 10px; font-size: 10px;"> At our company, we consider the protection of your privacy as a crucial
            principle. We understand that your personal information is one of our most critical assets. We store and
            process your information, including any sensitive financial information (as defined under the Information
            Technology Act, 2000), if any, on computers that are safeguarded by physical as well as reasonable
            technological security measures and procedures, as prescribed by the Information Technology Act 2000 and the
            rules thereunder. If you disagree with our current privacy policy or the way your information is being used
            or transferred, please refrain from using our website. </p>
        <h6 style="margin-bottom: 0px;">ELECTRONIC COMMUNICATIONS </h6>
        <p style="margin-top: 0px; margin-bottom: 10px; font-size: 10px;">When you use any of our services or send emails to us, you are communicating with us electronically. By using
            our services, you consent to receive electronic communications from us. We will communicate with you through
            email or by posting notices on our website or other services. You agree that all agreements, notices,
            disclosures, and other communications that we provide to you electronically fulfil any legal requirement
            that such communications be in writing. These legal requirements are in accordance with the Indian
            Information Technology Act, 2000, and its applicable rules, as well as the amended provisions regarding
            electronic records in various statutes, as amended by the Information Technology Act, 2000.</p>
    </div>
</body>
', 'V2'),
('2025-03-13 17:44:25.693000', 'cravxVisitorPortal', '<body style="font-size: 15px; letter-spacing: 0.55px;" >
     <div>
         <h6 style="margin-bottom: 0px;">TERMS OF USE </h6>
         <P style="margin-top: 0px; margin-bottom: 10px; font-size: 10px;">Welcome to ehr.com EHR and/or its affiliates provide website features and other products
             and services to you when you visit or shop at essayliving.com use Essay Living products or services, or use
             the software provided by Essay Living in connection with any of the foregoing. Essay Living provides the
             Services subject to the following conditions. This user agreement (“Terms and Conditions” or “T&C” or
             “Terms” or “Agreement”) is between you (“you” or “End User” or “your” or “Buyer” or “Customer” or
             “Registered User”) and Essay Living (“Company” or “us” or “we” or “essayliving.com”). This document is an
             electronic record in terms of the Information Technology Act, 2000 and rules there under as applicable and
             the amended provisions about electronic records in various statutes as amended by the Information Technology
             Act, 2000. This electronic record is generated by a computer system and does not require any physical or
             digital signatures. Notwithstanding anything contained or said in any other document, if there is a conflict
             between the terms mentioned herein below and any other document, the terms contained in the present T&C
             shall alone prevail for usage of the Site. </P>
 
         <h6 style="margin-bottom: 0px;">RIGHT TO CHANGE</h6>
         <p style="margin-top: 0px; margin-bottom: 10px; font-size: 10px;">EHR reserves the exclusive right to update or modify its Terms and Conditions at any time without
             prior notice. We, therefore, recommend that you review these Terms and Conditions every time you purchase
             products or use our website. </p>
 
         <h6 style="margin-bottom: 0px;">PRIVACY</h6>
         <p style="margin-top: 0px; margin-bottom: 10px; font-size: 10px;"> At our company, we consider the protection of your privacy as a crucial
             principle. We understand that your personal information is one of our most critical assets. We store and
             process your information, including any sensitive financial information (as defined under the Information
             Technology Act, 2000), if any, on computers that are safeguarded by physical as well as reasonable
             technological security measures and procedures, as prescribed by the Information Technology Act 2000 and the
             rules thereunder. If you disagree with our current privacy policy or the way your information is being used
             or transferred, please refrain from using our website. </p>
         <h6 style="margin-bottom: 0px;">ELECTRONIC COMMUNICATIONS </h6>
         <p style="margin-top: 0px; margin-bottom: 10px; font-size: 10px;">When you use any of our services or send emails to us, you are communicating with us electronically. By using
             our services, you consent to receive electronic communications from us. We will communicate with you through
             email or by posting notices on our website or other services. You agree that all agreements, notices,
             disclosures, and other communications that we provide to you electronically fulfil any legal requirement
             that such communications be in writing. These legal requirements are in accordance with the Indian
             Information Technology Act, 2000, and its applicable rules, as well as the amended provisions regarding
             electronic records in various statutes, as amended by the Information Technology Act, 2000.</p>
     </div>
 </body>
 ', 'V1');